services:
  - type: web
    name: employee-api
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan config:clear
      chmod -R 775 storage bootstrap/cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
